package controller

import (
	"github.com/RaymondCode/simple-demo/repository"
)

// 初始化使用Demo数据的数据库
func InitDemoData() {
	repository.GlobalDB.Where("1 = 1").Delete(&repository.UserDao{})
	repository.GlobalDB.Where("1 = 1").Delete(&repository.VideoDao{})
	repository.GlobalDB.Where("1 = 1").Delete(&repository.FavoriteVideoDao{})
	repository.GlobalDB.Where("1 = 1").Delete(&repository.CommentDao{})
	repository.GlobalDB.Where("1 = 1").Delete(&repository.FollowDao{})

	repository.GlobalDB.Create(&DemoUser)
	repository.GlobalDB.Create(&DemoVideos)
	repository.GlobalDB.Create(&DemoFavoriteVideos)
	repository.GlobalDB.Create(&DemoComments)
	repository.GlobalDB.Create(&DemoFollows)
}

var DemoUser = []repository.UserDao{
	{
		Id:            1,
		Name:          "user1@1.com",
		FollowCount:   3,
		FollowerCount: 2,
		IsFollow:      false,
		Token:         "user1@1.com111111",
	},
	{
		Id:            2,
		Name:          "user2@2.com",
		FollowCount:   2,
		FollowerCount: 2,
		IsFollow:      false,
		Token:         "user2@2.com222222",
	},
	{
		Id:            3,
		Name:          "user3@3.com",
		FollowCount:   2,
		FollowerCount: 2,
		IsFollow:      false,
		Token:         "user3@3.com333333",
	},
	{
		Id:            4,
		Name:          "user4@4.com",
		FollowCount:   2,
		FollowerCount: 3,
		IsFollow:      false,
		Token:         "user4@4.com444444",
	},
	{
		Id:            5,
		Name:          "user5@5.com",
		FollowCount:   1,
		FollowerCount: 1,
		IsFollow:      false,
		Token:         "user5@5.com555555",
	},
}

var DemoVideos = []repository.VideoDao{
	{
		Id:            1,
		AuthorId:      DemoUser[0].Id,
		PlayUrl:       serverUrl + "static/bear.mp4",
		CoverUrl:      "https://cdn.pixabay.com/photo/2016/03/27/18/10/bear-1283347_1280.jpg",
		FavoriteCount: 3,
		CommentCount:  1,
		IsFavorite:    false,
		Title:         "Bear - published at time 1",
		PublishTime:   1,
	},
	{
		Id:            2,
		AuthorId:      DemoUser[1].Id,
		PlayUrl:       "https://assets.mixkit.co/videos/preview/mixkit-texture-of-different-fruits-42959-large.mp4",
		CoverUrl:      "https://mixkit.imgix.net/videos/preview/mixkit-texture-of-different-fruits-42959-0.jpg?q=80&auto=format%2Ccompress",
		FavoriteCount: 1,
		CommentCount:  2,
		IsFavorite:    false,
		Title:         "Texture of different fruits - published at time 2",
		PublishTime:   2,
	},
	{
		Id:            3,
		AuthorId:      DemoUser[2].Id,
		PlayUrl:       "https://assets.mixkit.co/videos/preview/mixkit-ingredients-for-a-healthy-breakfast-3795-large.mp4",
		CoverUrl:      "https://mixkit.imgix.net/videos/preview/mixkit-ingredients-for-a-healthy-breakfast-3795-0.jpg?q=80&auto=format%2Ccompress",
		FavoriteCount: 1,
		CommentCount:  0,
		IsFavorite:    false,
		Title:         "Ingredients for a healthy breakfast - published at time 3",
		PublishTime:   3,
	},
	{
		Id:            4,
		AuthorId:      DemoUser[3].Id,
		PlayUrl:       "https://assets.mixkit.co/videos/preview/mixkit-fresh-apples-in-a-row-on-a-natural-background-42946-large.mp4",
		CoverUrl:      "https://mixkit.imgix.net/videos/preview/mixkit-fresh-apples-in-a-row-on-a-natural-background-42946-0.jpg?q=80&auto=format%2Ccompress",
		FavoriteCount: 1,
		CommentCount:  0,
		IsFavorite:    false,
		Title:         "Fresh apples - published at time 4",
		PublishTime:   4,
	},
	{
		Id:            5,
		AuthorId:      DemoUser[4].Id,
		PlayUrl:       "https://assets.mixkit.co/videos/preview/mixkit-a-bunch-of-strawberries-falling-through-water-15973-large.mp4",
		CoverUrl:      "https://mixkit.imgix.net/videos/preview/mixkit-a-bunch-of-strawberries-falling-through-water-15973-3.jpg?q=80&auto=format%2Ccompress",
		FavoriteCount: 0,
		CommentCount:  0,
		IsFavorite:    false,
		Title:         "A bunch of strawberries - published at time 5",
		PublishTime:   5,
	},
	{
		Id:            6,
		AuthorId:      DemoUser[0].Id,
		PlayUrl:       "https://assets.mixkit.co/videos/preview/mixkit-cutting-through-a-fresh-pizza-20913-large.mp4",
		CoverUrl:      "https://mixkit.imgix.net/videos/preview/mixkit-cutting-through-a-fresh-pizza-20913-0.jpg?q=80&auto=format%2Ccompress",
		FavoriteCount: 0,
		CommentCount:  0,
		IsFavorite:    false,
		Title:         "A fresh pizza - published at time 6",
		PublishTime:   6,
	},
	{
		Id:            7,
		AuthorId:      DemoUser[1].Id,
		PlayUrl:       "https://assets.mixkit.co/videos/preview/mixkit-hamburger-with-french-fries-and-soda-29710-large.mp4",
		CoverUrl:      "https://mixkit.imgix.net/videos/preview/mixkit-hamburger-with-french-fries-and-soda-29710-0.jpg?q=80&auto=format%2Ccompress",
		FavoriteCount: 0,
		CommentCount:  0,
		IsFavorite:    false,
		Title:         "Hamburger with French fries and soda - published at time 7",
		PublishTime:   7,
	},
	{
		Id:            8,
		AuthorId:      DemoUser[2].Id,
		PlayUrl:       "https://assets.mixkit.co/videos/preview/mixkit-serving-juice-in-a-glass-with-some-oranges-on-a-10428-large.mp4",
		CoverUrl:      "https://mixkit.imgix.net/videos/preview/mixkit-serving-juice-in-a-glass-with-some-oranges-on-a-10428-0.jpg?q=80&auto=format%2Ccompress",
		FavoriteCount: 0,
		CommentCount:  0,
		IsFavorite:    false,
		Title:         "Serving juice - published at time 8",
		PublishTime:   8,
	},
	{
		Id:            9,
		AuthorId:      DemoUser[3].Id,
		PlayUrl:       "https://assets.mixkit.co/videos/preview/mixkit-fresh-orange-slices-3697-large.mp4",
		CoverUrl:      "https://mixkit.imgix.net/videos/preview/mixkit-fresh-orange-slices-3697-0.jpg?q=80&auto=format%2Ccompress",
		FavoriteCount: 0,
		CommentCount:  0,
		IsFavorite:    false,
		Title:         "Fresh orange slices - published at time 9",
		PublishTime:   9,
	},
	{
		Id:            10,
		AuthorId:      DemoUser[4].Id,
		PlayUrl:       "https://assets.mixkit.co/videos/preview/mixkit-rotating-bowl-with-fruit-on-a-white-background-10424-large.mp4",
		CoverUrl:      "https://mixkit.imgix.net/videos/preview/mixkit-rotating-bowl-with-fruit-on-a-white-background-10424-0.jpg?q=80&auto=format%2Ccompress",
		FavoriteCount: 0,
		CommentCount:  0,
		IsFavorite:    false,
		Title:         "Rotating bowl with fruit - published at time 10",
		PublishTime:   10,
	},
	{
		Id:            11,
		AuthorId:      DemoUser[0].Id,
		PlayUrl:       "https://assets.mixkit.co/videos/preview/mixkit-bowl-with-yogurt-served-with-chopped-fruit-10436-large.mp4",
		CoverUrl:      "https://mixkit.imgix.net/videos/preview/mixkit-bowl-with-yogurt-served-with-chopped-fruit-10436-0.jpg?q=80&auto=format%2Ccompress",
		FavoriteCount: 0,
		CommentCount:  0,
		IsFavorite:    false,
		Title:         "Bowl with yogurt - published at time 11",
		PublishTime:   11,
	},
	{
		Id:            12,
		AuthorId:      DemoUser[1].Id,
		PlayUrl:       "https://assets.mixkit.co/videos/preview/mixkit-rich-watermelon-cut-into-slices-on-a-white-background-4936-large.mp4",
		CoverUrl:      "https://mixkit.imgix.net/videos/preview/mixkit-rich-watermelon-cut-into-slices-on-a-white-background-4936-0.jpg?q=80&auto=format%2Ccompress",
		FavoriteCount: 0,
		CommentCount:  0,
		IsFavorite:    false,
		Title:         "Rich watermelon - published at time 12",
		PublishTime:   12,
	},
	{
		Id:            13,
		AuthorId:      DemoUser[2].Id,
		PlayUrl:       "https://assets.mixkit.co/videos/preview/mixkit-valentines-day-dessert-cupcake-3234-large.mp4",
		CoverUrl:      "https://mixkit.imgix.net/videos/preview/mixkit-valentines-day-dessert-cupcake-3234-0.jpg?q=80&auto=format%2Ccompress",
		FavoriteCount: 0,
		CommentCount:  0,
		IsFavorite:    false,
		Title:         "Valentine's Day dessert cupcake - published at time 13",
		PublishTime:   13,
	},
	{
		Id:            14,
		AuthorId:      DemoUser[3].Id,
		PlayUrl:       "https://assets.mixkit.co/videos/preview/mixkit-eating-pasta-with-a-fork-16589-large.mp4",
		CoverUrl:      "https://mixkit.imgix.net/videos/preview/mixkit-eating-pasta-with-a-fork-16589-0.jpg?q=80&auto=format%2Ccompress",
		FavoriteCount: 0,
		CommentCount:  0,
		IsFavorite:    false,
		Title:         "Eating pasta with a fork - published at time 14",
		PublishTime:   14,
	},
	{
		Id:            15,
		AuthorId:      DemoUser[4].Id,
		PlayUrl:       "https://assets.mixkit.co/videos/preview/mixkit-salmon-chunks-with-lemon-26346-large.mp4",
		CoverUrl:      "https://mixkit.imgix.net/videos/preview/mixkit-salmon-chunks-with-lemon-26346-2.jpg?q=80&auto=format%2Ccompress",
		FavoriteCount: 0,
		CommentCount:  0,
		IsFavorite:    false,
		Title:         "Salmon chunks with lemon - published at time 15",
		PublishTime:   15,
	},
	{
		Id:            16,
		AuthorId:      DemoUser[0].Id,
		PlayUrl:       "https://assets.mixkit.co/videos/preview/mixkit-green-wheat-moving-with-the-wind-9901-large.mp4",
		CoverUrl:      "https://mixkit.imgix.net/videos/preview/mixkit-green-wheat-moving-with-the-wind-9901-0.jpg?q=80&auto=format%2Ccompress",
		FavoriteCount: 0,
		CommentCount:  0,
		IsFavorite:    false,
		Title:         "Green wheat - published at time 16",
		PublishTime:   16,
	},
	{
		Id:            17,
		AuthorId:      DemoUser[1].Id,
		PlayUrl:       "https://assets.mixkit.co/videos/preview/mixkit-fresh-salmon-sushi-close-up-32518-large.mp4",
		CoverUrl:      "https://mixkit.imgix.net/videos/preview/mixkit-fresh-salmon-sushi-close-up-32518-0.jpg?q=80&auto=format%2Ccompress",
		FavoriteCount: 0,
		CommentCount:  0,
		IsFavorite:    false,
		Title:         "Fresh salmon sushi - published at time 17",
		PublishTime:   17,
	},
	{
		Id:            18,
		AuthorId:      DemoUser[2].Id,
		PlayUrl:       "https://assets.mixkit.co/videos/preview/mixkit-neapolitan-flavor-ice-cream-in-detail-18329-large.mp4",
		CoverUrl:      "https://mixkit.imgix.net/videos/preview/mixkit-neapolitan-flavor-ice-cream-in-detail-18329-0.jpg?q=80&auto=format%2Ccompress",
		FavoriteCount: 0,
		CommentCount:  0,
		IsFavorite:    false,
		Title:         "Flavor ice cream - published at time 18",
		PublishTime:   18,
	},
	{
		Id:            19,
		AuthorId:      DemoUser[3].Id,
		PlayUrl:       "https://assets.mixkit.co/videos/preview/mixkit-banana-slices-3695-large.mp4",
		CoverUrl:      "https://mixkit.imgix.net/videos/preview/mixkit-banana-slices-3695-0.jpg?q=80&auto=format%2Ccompress",
		FavoriteCount: 0,
		CommentCount:  0,
		IsFavorite:    false,
		Title:         "Banana slices - published at time 19",
		PublishTime:   19,
	},
	{
		Id:            20,
		AuthorId:      DemoUser[4].Id,
		PlayUrl:       "https://assets.mixkit.co/videos/preview/mixkit-citrus-grapefruit-slices-3699-large.mp4",
		CoverUrl:      "https://mixkit.imgix.net/videos/preview/mixkit-citrus-grapefruit-slices-3699-0.jpg?q=80&auto=format%2Ccompress",
		FavoriteCount: 0,
		CommentCount:  0,
		IsFavorite:    false,
		Title:         "Citrus grapefruit slices - published at time 20",
		PublishTime:   20,
	},
	{
		Id:            21,
		AuthorId:      DemoUser[0].Id,
		PlayUrl:       "https://assets.mixkit.co/videos/preview/mixkit-glass-bowl-full-of-red-berries-seen-in-detail-10423-large.mp4",
		CoverUrl:      "https://mixkit.imgix.net/videos/preview/mixkit-glass-bowl-full-of-red-berries-seen-in-detail-10423-0.jpg?q=80&auto=format%2Ccompress",
		FavoriteCount: 0,
		CommentCount:  0,
		IsFavorite:    false,
		Title:         "Red berries - published at time 21",
		PublishTime:   21,
	},
	{
		Id:            22,
		AuthorId:      DemoUser[1].Id,
		PlayUrl:       "https://assets.mixkit.co/videos/preview/mixkit-wet-grapes-texture-spinning-shot-9542-large.mp4",
		CoverUrl:      "https://mixkit.imgix.net/videos/preview/mixkit-wet-grapes-texture-spinning-shot-9542-0.jpg?q=80&auto=format%2Ccompress",
		FavoriteCount: 0,
		CommentCount:  0,
		IsFavorite:    false,
		Title:         "Wet grapes texture - published at time 22",
		PublishTime:   22,
	},
	{
		Id:            23,
		AuthorId:      DemoUser[2].Id,
		PlayUrl:       "https://assets.mixkit.co/videos/preview/mixkit-squeezing-lemon-on-seafood-16439-large.mp4",
		CoverUrl:      "https://mixkit.imgix.net/videos/preview/mixkit-squeezing-lemon-on-seafood-16439-0.jpg?q=80&auto=format%2Ccompress",
		FavoriteCount: 1,
		CommentCount:  0,
		IsFavorite:    false,
		Title:         "Squeezing lemon on seafood - published at time 23",
		PublishTime:   23,
	},
	{
		Id:            24,
		AuthorId:      DemoUser[3].Id,
		PlayUrl:       "https://assets.mixkit.co/videos/preview/mixkit-fruit-composition-with-a-coconut-in-the-foreground-9558-large.mp4",
		CoverUrl:      "https://mixkit.imgix.net/videos/preview/mixkit-fruit-composition-with-a-coconut-in-the-foreground-9558-0.jpg?q=80&auto=format%2Ccompress",
		FavoriteCount: 1,
		CommentCount:  0,
		IsFavorite:    false,
		Title:         "Fruit composition with a coconut - published at time 24",
		PublishTime:   24,
	},
	{
		Id:            25,
		AuthorId:      DemoUser[4].Id,
		PlayUrl:       "https://assets.mixkit.co/videos/preview/mixkit-hamburger-with-fries-and-a-soda-on-a-dark-background-38664-large.mp4",
		CoverUrl:      "https://mixkit.imgix.net/videos/preview/mixkit-hamburger-with-fries-and-a-soda-on-a-dark-background-38664-0.jpg?q=80&auto=format%2Ccompress",
		FavoriteCount: 1,
		CommentCount:  0,
		IsFavorite:    false,
		Title:         "Hamburger with fries and a soda - published at time 25",
		PublishTime:   25,
	},
	{
		Id:            26,
		AuthorId:      DemoUser[0].Id,
		PlayUrl:       "https://assets.mixkit.co/videos/preview/mixkit-plate-of-wings-rotating-on-a-black-background-38576-large.mp4",
		CoverUrl:      "https://mixkit.imgix.net/videos/preview/mixkit-plate-of-wings-rotating-on-a-black-background-38576-0.jpg?q=80&auto=format%2Ccompress",
		FavoriteCount: 1,
		CommentCount:  0,
		IsFavorite:    false,
		Title:         "Plate of wings - published at time 26",
		PublishTime:   26,
	},
	{
		Id:            27,
		AuthorId:      DemoUser[1].Id,
		PlayUrl:       "https://assets.mixkit.co/videos/preview/mixkit-played-with-grapefruits-wine-and-cheese-28812-large.mp4",
		CoverUrl:      "https://mixkit.imgix.net/videos/preview/mixkit-played-with-grapefruits-wine-and-cheese-28812-0.jpg?q=80&auto=format%2Ccompress",
		FavoriteCount: 1,
		CommentCount:  0,
		IsFavorite:    false,
		Title:         "Played with grapefruits - published at time 27",
		PublishTime:   27,
	},
	{
		Id:            28,
		AuthorId:      DemoUser[2].Id,
		PlayUrl:       "https://assets.mixkit.co/videos/preview/mixkit-pasta-eggs-wheat-and-flour-14506-large.mp4",
		CoverUrl:      "https://mixkit.imgix.net/videos/preview/mixkit-pasta-eggs-wheat-and-flour-14506-0.jpg?q=80&auto=format%2Ccompress",
		FavoriteCount: 2,
		CommentCount:  0,
		IsFavorite:    false,
		Title:         "Pasta, eggs, wheat - published at time 28",
		PublishTime:   28,
	},
	{
		Id:            29,
		AuthorId:      DemoUser[3].Id,
		PlayUrl:       "https://assets.mixkit.co/videos/preview/mixkit-detox-diet-smoothies-and-vegetables-closeup-5688-large.mp4",
		CoverUrl:      "https://mixkit.imgix.net/videos/preview/mixkit-detox-diet-smoothies-and-vegetables-closeup-5688-0.jpg?q=80&auto=format%2Ccompress",
		FavoriteCount: 3,
		CommentCount:  0,
		IsFavorite:    false,
		Title:         "Smoothies and vegetables - published at time 29",
		PublishTime:   29,
	},
	{
		Id:            30,
		AuthorId:      DemoUser[4].Id,
		PlayUrl:       "https://assets.mixkit.co/videos/preview/mixkit-chopped-pieces-of-cheese-in-the-counter-31959-large.mp4",
		CoverUrl:      "https://mixkit.imgix.net/videos/preview/mixkit-chopped-pieces-of-cheese-in-the-counter-31959-0.jpg?q=80&auto=format%2Ccompress",
		FavoriteCount: 2,
		CommentCount:  2,
		IsFavorite:    false,
		Title:         "Chopped pieces of cheese - published at time 30",
		PublishTime:   30,
	},
	{
		Id:            31,
		AuthorId:      DemoUser[4].Id,
		PlayUrl:       "https://assets.mixkit.co/videos/preview/mixkit-falling-sweet-decorations-into-the-doughnut-30791-large.mp4",
		CoverUrl:      "https://mixkit.imgix.net/videos/preview/mixkit-falling-sweet-decorations-into-the-doughnut-30791-0.jpg?q=80&auto=format%2Ccompress",
		FavoriteCount: 3,
		CommentCount:  5,
		IsFavorite:    false,
		Title:         "Doughnut - published at time 31",
		PublishTime:   31,
	},
}

var DemoFavoriteVideos = []repository.FavoriteVideoDao{
	{Token: "user3@3.com333333", VideoId: 31},
	{Token: "user4@4.com444444", VideoId: 31},
	{Token: "user5@5.com555555", VideoId: 31},
	{Token: "user1@1.com111111", VideoId: 30},
	{Token: "user2@2.com222222", VideoId: 30},
	{Token: "user3@3.com333333", VideoId: 29},
	{Token: "user4@4.com444444", VideoId: 29},
	{Token: "user5@5.com555555", VideoId: 29},
	{Token: "user3@3.com333333", VideoId: 28},
	{Token: "user4@4.com444444", VideoId: 28},
	{Token: "user1@1.com111111", VideoId: 27},
	{Token: "user2@2.com222222", VideoId: 26},
	{Token: "user3@3.com333333", VideoId: 25},
	{Token: "user4@4.com444444", VideoId: 24},
	{Token: "user5@5.com555555", VideoId: 23},
	{Token: "user3@3.com333333", VideoId: 4},
	{Token: "user4@4.com444444", VideoId: 3},
	{Token: "user5@5.com555555", VideoId: 2},
	{Token: "user1@1.com111111", VideoId: 1},
	{Token: "user2@2.com222222", VideoId: 1},
	{Token: "user4@4.com444444", VideoId: 1},
}

var DemoComments = []repository.CommentDao{
	{
		Id:          1,
		UserId:      DemoUser[0].Id,
		VideoId:     31,
		Content:     "user1 comment video31 at time 50",
		CreateDate:  "05-05",
		PublishTime: 50,
	},
	{
		Id:          2,
		UserId:      DemoUser[1].Id,
		VideoId:     31,
		Content:     "user2 comment video31 at time 49",
		CreateDate:  "05-04",
		PublishTime: 49,
	},
	{
		Id:          3,
		UserId:      DemoUser[2].Id,
		VideoId:     31,
		Content:     "user3 comment video31 at time 48",
		CreateDate:  "05-03",
		PublishTime: 48,
	},
	{
		Id:          4,
		UserId:      DemoUser[3].Id,
		VideoId:     31,
		Content:     "user4 comment video31 at time 47",
		CreateDate:  "05-02",
		PublishTime: 47,
	},
	{
		Id:          5,
		UserId:      DemoUser[4].Id,
		VideoId:     31,
		Content:     "user5 comment video31 at time 46",
		CreateDate:  "05-01",
		PublishTime: 46,
	},
	{
		Id:          6,
		UserId:      DemoUser[0].Id,
		VideoId:     30,
		Content:     "user1 comment video30 at time 45",
		CreateDate:  "05-02",
		PublishTime: 45,
	},
	{
		Id:          7,
		UserId:      DemoUser[1].Id,
		VideoId:     30,
		Content:     "user2 comment video30 at time 44",
		CreateDate:  "05-01",
		PublishTime: 44,
	},
	{
		Id:          8,
		UserId:      DemoUser[2].Id,
		VideoId:     2,
		Content:     "user3 comment video2 at time 43",
		CreateDate:  "05-03",
		PublishTime: 43,
	},
	{
		Id:          9,
		UserId:      DemoUser[3].Id,
		VideoId:     2,
		Content:     "user4 comment video2 at time 42",
		CreateDate:  "05-02",
		PublishTime: 42,
	},
	{
		Id:          10,
		UserId:      DemoUser[4].Id,
		VideoId:     1,
		Content:     "user5 comment video1 at time 41",
		CreateDate:  "05-01",
		PublishTime: 41,
	},
}

var DemoFollows = []repository.FollowDao{
	{UserId: DemoUser[0].Id, ToUserId: DemoUser[1].Id},
	{UserId: DemoUser[0].Id, ToUserId: DemoUser[2].Id},
	{UserId: DemoUser[0].Id, ToUserId: DemoUser[3].Id},
	{UserId: DemoUser[1].Id, ToUserId: DemoUser[0].Id},
	{UserId: DemoUser[1].Id, ToUserId: DemoUser[3].Id},
	{UserId: DemoUser[2].Id, ToUserId: DemoUser[3].Id},
	{UserId: DemoUser[2].Id, ToUserId: DemoUser[4].Id},
	{UserId: DemoUser[3].Id, ToUserId: DemoUser[1].Id},
	{UserId: DemoUser[3].Id, ToUserId: DemoUser[0].Id},
	{UserId: DemoUser[4].Id, ToUserId: DemoUser[2].Id},
}
